#!/usr/bin/env bash
set -Eeuo pipefail
ENV_FILE="${1:-/etc/elk-auto/elk.env}"
[[ -f "$ENV_FILE" ]] || exit 1
# shellcheck disable=SC1090
source "$ENV_FILE"
: "${HEALTH_MONITOR_LOG:=/var/log/elk-health-monitor.log}"
: "${HEALTH_DISK_WARN_PERCENT:=85}"
: "${HEALTH_DISK_CRIT_PERCENT:=92}"
: "${HEALTH_AUTO_PAUSE_FILE_INGEST_ON_CRITICAL:=false}"
: "${ES_HTTP_PORT:=9200}"
: "${ES_SECURITY_ENABLED:=true}"
: "${ELASTIC_USERNAME:=elastic}"
: "${SECRETS_FILE:=/root/.elk-auto-installer/secrets.env}"
: "${ES_PATH_DATA:=/var/lib/elasticsearch}"
: "${FILE_INGEST_STAGING_DIR:=/var/lib/elk-file-ingest/staging}"
istrue(){ [[ "${1,,}" =~ ^(1|true|yes|y|on)$ ]]; }
ts(){ date '+%Y-%m-%d %H:%M:%S'; }
log(){ printf '[%s] %s\n' "$(ts)" "$*" | tee -a "$HEALTH_MONITOR_LOG"; }
mkdir -p "$(dirname "$HEALTH_MONITOR_LOG")"; touch "$HEALTH_MONITOR_LOG"; chmod 640 "$HEALTH_MONITOR_LOG" || true

ELASTIC_PASSWORD="${ELASTIC_PASSWORD:-}"
if [[ -z "$ELASTIC_PASSWORD" && -f "$SECRETS_FILE" ]]; then
  # trusted root-only file generated by installer
  # shellcheck disable=SC1090
  source "$SECRETS_FILE"
fi
CA=/etc/elasticsearch/certs/http_ca.crt
if [[ -f "$CA" ]]; then URL="https://127.0.0.1:${ES_HTTP_PORT}"; else URL="http://127.0.0.1:${ES_HTTP_PORT}"; fi
curl_args=(-sS --connect-timeout 3 --max-time 10)
[[ -f "$CA" ]] && curl_args+=(--cacert "$CA")
if istrue "$ES_SECURITY_ENABLED" && [[ -n "${ELASTIC_PASSWORD:-}" ]]; then curl_args+=(-u "${ELASTIC_USERNAME}:${ELASTIC_PASSWORD}"); fi

for svc in elasticsearch kibana logstash nginx vsftpd; do
  if systemctl list-unit-files "$svc.service" >/dev/null 2>&1; then
    if systemctl is-active --quiet "$svc"; then log "OK service=$svc"; else log "CRIT service=$svc inactive"; fi
  fi
done

if resp=$(curl "${curl_args[@]}" "$URL/_cluster/health" 2>/dev/null); then
  status=$(jq -r '.status // "unknown"' <<<"$resp")
  unassigned=$(jq -r '.unassigned_shards // -1' <<<"$resp")
  nodes=$(jq -r '.number_of_nodes // -1' <<<"$resp")
  log "ES cluster_status=$status nodes=$nodes unassigned_shards=$unassigned"
else
  log "CRIT Elasticsearch API 응답 실패: $URL"
fi

critical=0
for path in "$ES_PATH_DATA" "$FILE_INGEST_STAGING_DIR"; do
  [[ -e "$path" ]] || continue
  use=$(df -P "$path" | awk 'NR==2{gsub(/%/,"",$5); print $5}')
  avail=$(df -Ph "$path" | awk 'NR==2{print $4}')
  if (( use >= HEALTH_DISK_CRIT_PERCENT )); then
    log "CRIT disk path=$path use=${use}% avail=$avail"; critical=1
  elif (( use >= HEALTH_DISK_WARN_PERCENT )); then
    log "WARN disk path=$path use=${use}% avail=$avail"
  else
    log "OK disk path=$path use=${use}% avail=$avail"
  fi
done

if (( critical == 1 )) && istrue "$HEALTH_AUTO_PAUSE_FILE_INGEST_ON_CRITICAL"; then
  if systemctl is-active --quiet elk-log-ingest.timer 2>/dev/null; then
    systemctl stop elk-log-ingest.timer || true
    log "CRIT 디스크 보호를 위해 elk-log-ingest.timer 자동 중지"
  fi
fi
